global:
  keyboard: ansi_60      # --keyboard <keyboard>
  layout: colemak        # --layout <layout>
  frequency: python      # --language <frequency>
  corpus: english_bools  # --corpus <corpus>

display:
  show_modifiers: true     # -m
  show_layout: true        # -l
  show_key_codes: false    # -k

  show_row_numbers: false  # -r
  show_fingers: false      # -f
  show_frequencies: true   # -p
  show_home_keys: true     # -hk

  color_by: freq           # -c <"frequency" | "row" | "hand" | "finger" | "none">

frequencies:
  file_paths:                 # -f <file [...]>
  only_layout_mappings: true  # -m
