[global]
frequencies = "data/frequencies/russian.yaml"  # -language <frequencies file>
keyboard = "data/keyboards/ansi_60.yaml"       # -keyboard <keyboard file>
layout = "data/layouts/jcuken.yaml"            # -layout <layout file>

[display]
show_modifiers = true    # -m
show_layout = true       # -l

show_rows = false        # -r
show_fingers = false     # -f
show_frequencies = true  # -p

color_by = "Frequency"  # -c <"Frequency" | "Row" | "Hand" | "Finger" | "None">
