# Settings
# keyboard: str   # --keyboard <keyboard> 
# layout: str     # --layout <layout>  
# corpus: str     # --corpus <corpus> 

anchors:
  presets: &default
    keyboard: ansi_60    
    layout: en/qwerty   
    corpus: english     

  qwerty: &qwerty
    layout: en/qwerty
    corpus: english

  jcuken: &jcuken
    layout: ru/jcuken
    corpus: russian

# Global settings
<<: *default
<<: *qwerty

layout: en/dhorf
