anchors:
  presets: &default
    keyboard: ansi_60   # --keyboard <keyboard>
    layout: en/qwerty   # --layout <layout>
    frequency: english  # --language <frequency>
    corpus: english     # --corpus <corpus>

  qwerty: &qwerty
    layout: en/qwerty
    frequency: english
    corpus: english
  
  jcuken: &jcuken
    layout: ru/jcuken
    frequency: obsidian
    corpus: russian

# Global settings
<<: *default
<<: *qwerty
keyboard: matrix_60
